server.port=8080

# SQLite file (relative to project root)
spring.datasource.url=jdbc:sqlite:./data/todos.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


# Custom SQLite Dialect compatible with Hibernate 5.4.x (Spring Boot 2.3.x)
spring.jpa.database-platform=com.starterkit.springboot.config.SQLiteDialect


# Logs do filter de requests (vai para o terminal)
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG